Fix --speak= can take no value

diff --git a/argparser b/argparser
--- a/argparser
+++ b/argparser
@@ -2,7 +2,7 @@
 set -o nounset
 
 parse () {
-    local mode="$1" eff flag1
+    local mode="$1" eff flag1 equalvalue
     shift
     shiftnum=1
     case "$mode" in
@@ -49,7 +49,15 @@ parse () {
         shiftnum=2
         ;;
     speak=*,2)
-        speak="${eff#speak=}"
+        equalvalue="${eff#speak=}"
+        eff="${eff%%=*}"
+        if test "$equalvalue"
+        then
+            speak="$equalvalue"
+        else
+            >&2 printf "error: %s requires a value\n" "$eff"
+            exit 1
+        fi
         ;;
     speak,no)
         speak=""
